services:
  - type: web
    name: keycloak-on-render
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: start-dev
    autoDeploy: true
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
    ports: 
      - 8080
